[package]
name = "intel-4004"
version = "0.1.0"
edition = "2024"

[features]
default = []
debug = ["msc-4/debug"]

[dependencies]
msc-4 = { path = "src/msc-4" }
clap = { version = "4", features = ["derive"] }
